// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	FencingToken  int64                  `protobuf:"varint,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	TxnId         string                 `protobuf:"bytes,5,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	TxnExplicit   bool                   `protobuf:"varint,6,opt,name=txn_explicit,json=txnExplicit,proto3" json:"txn_explicit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Lease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Lease) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Lease) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Lease) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Lease) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *Lease) GetTxnExplicit() bool {
	if x != nil {
		return x.TxnExplicit
	}
	return false
}

type LockMeta struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Lease                     *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Version                   int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	StateEtag                 string                 `protobuf:"bytes,3,opt,name=state_etag,json=stateEtag,proto3" json:"state_etag,omitempty"`
	UpdatedAtUnix             int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	FencingToken              int64                  `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	StateDescriptor           []byte                 `protobuf:"bytes,6,opt,name=state_descriptor,json=stateDescriptor,proto3" json:"state_descriptor,omitempty"`
	StatePlaintextBytes       int64                  `protobuf:"varint,7,opt,name=state_plaintext_bytes,json=statePlaintextBytes,proto3" json:"state_plaintext_bytes,omitempty"`
	PublishedVersion          int64                  `protobuf:"varint,8,opt,name=published_version,json=publishedVersion,proto3" json:"published_version,omitempty"`
	Attributes                *structpb.Struct       `protobuf:"bytes,9,opt,name=attributes,proto3" json:"attributes,omitempty"`
	StagedTxnId               string                 `protobuf:"bytes,10,opt,name=staged_txn_id,json=stagedTxnId,proto3" json:"staged_txn_id,omitempty"`
	StagedStateEtag           string                 `protobuf:"bytes,11,opt,name=staged_state_etag,json=stagedStateEtag,proto3" json:"staged_state_etag,omitempty"`
	StagedStateDescriptor     []byte                 `protobuf:"bytes,12,opt,name=staged_state_descriptor,json=stagedStateDescriptor,proto3" json:"staged_state_descriptor,omitempty"`
	StagedStatePlaintextBytes int64                  `protobuf:"varint,13,opt,name=staged_state_plaintext_bytes,json=stagedStatePlaintextBytes,proto3" json:"staged_state_plaintext_bytes,omitempty"`
	StagedVersion             int64                  `protobuf:"varint,14,opt,name=staged_version,json=stagedVersion,proto3" json:"staged_version,omitempty"`
	StagedAttributes          map[string]string      `protobuf:"bytes,15,rep,name=staged_attributes,json=stagedAttributes,proto3" json:"staged_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StagedRemove              bool                   `protobuf:"varint,16,opt,name=staged_remove,json=stagedRemove,proto3" json:"staged_remove,omitempty"`
	Attachments               []*Attachment          `protobuf:"bytes,17,rep,name=attachments,proto3" json:"attachments,omitempty"`
	StagedAttachments         []*StagedAttachment    `protobuf:"bytes,18,rep,name=staged_attachments,json=stagedAttachments,proto3" json:"staged_attachments,omitempty"`
	StagedAttachmentDeletes   []string               `protobuf:"bytes,19,rep,name=staged_attachment_deletes,json=stagedAttachmentDeletes,proto3" json:"staged_attachment_deletes,omitempty"`
	StagedAttachmentsClear    bool                   `protobuf:"varint,20,opt,name=staged_attachments_clear,json=stagedAttachmentsClear,proto3" json:"staged_attachments_clear,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LockMeta) Reset() {
	*x = LockMeta{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockMeta) ProtoMessage() {}

func (x *LockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockMeta.ProtoReflect.Descriptor instead.
func (*LockMeta) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *LockMeta) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *LockMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LockMeta) GetStateEtag() string {
	if x != nil {
		return x.StateEtag
	}
	return ""
}

func (x *LockMeta) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *LockMeta) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockMeta) GetStateDescriptor() []byte {
	if x != nil {
		return x.StateDescriptor
	}
	return nil
}

func (x *LockMeta) GetStatePlaintextBytes() int64 {
	if x != nil {
		return x.StatePlaintextBytes
	}
	return 0
}

func (x *LockMeta) GetPublishedVersion() int64 {
	if x != nil {
		return x.PublishedVersion
	}
	return 0
}

func (x *LockMeta) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LockMeta) GetStagedTxnId() string {
	if x != nil {
		return x.StagedTxnId
	}
	return ""
}

func (x *LockMeta) GetStagedStateEtag() string {
	if x != nil {
		return x.StagedStateEtag
	}
	return ""
}

func (x *LockMeta) GetStagedStateDescriptor() []byte {
	if x != nil {
		return x.StagedStateDescriptor
	}
	return nil
}

func (x *LockMeta) GetStagedStatePlaintextBytes() int64 {
	if x != nil {
		return x.StagedStatePlaintextBytes
	}
	return 0
}

func (x *LockMeta) GetStagedVersion() int64 {
	if x != nil {
		return x.StagedVersion
	}
	return 0
}

func (x *LockMeta) GetStagedAttributes() map[string]string {
	if x != nil {
		return x.StagedAttributes
	}
	return nil
}

func (x *LockMeta) GetStagedRemove() bool {
	if x != nil {
		return x.StagedRemove
	}
	return false
}

func (x *LockMeta) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *LockMeta) GetStagedAttachments() []*StagedAttachment {
	if x != nil {
		return x.StagedAttachments
	}
	return nil
}

func (x *LockMeta) GetStagedAttachmentDeletes() []string {
	if x != nil {
		return x.StagedAttachmentDeletes
	}
	return nil
}

func (x *LockMeta) GetStagedAttachmentsClear() bool {
	if x != nil {
		return x.StagedAttachmentsClear
	}
	return false
}

type Attachment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size            int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType     string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Descriptor_     []byte                 `protobuf:"bytes,5,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix   int64                  `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	PlaintextBytes  int64                  `protobuf:"varint,8,opt,name=plaintext_bytes,json=plaintextBytes,proto3" json:"plaintext_bytes,omitempty"`
	PlaintextSha256 string                 `protobuf:"bytes,9,opt,name=plaintext_sha256,json=plaintextSha256,proto3" json:"plaintext_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Attachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetDescriptor_() []byte {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Attachment) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Attachment) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Attachment) GetPlaintextBytes() int64 {
	if x != nil {
		return x.PlaintextBytes
	}
	return 0
}

func (x *Attachment) GetPlaintextSha256() string {
	if x != nil {
		return x.PlaintextSha256
	}
	return ""
}

type StagedAttachment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size             int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType      string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	StagedDescriptor []byte                 `protobuf:"bytes,5,opt,name=staged_descriptor,json=stagedDescriptor,proto3" json:"staged_descriptor,omitempty"`
	CreatedAtUnix    int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix    int64                  `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	PlaintextBytes   int64                  `protobuf:"varint,8,opt,name=plaintext_bytes,json=plaintextBytes,proto3" json:"plaintext_bytes,omitempty"`
	PlaintextSha256  string                 `protobuf:"bytes,9,opt,name=plaintext_sha256,json=plaintextSha256,proto3" json:"plaintext_sha256,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StagedAttachment) Reset() {
	*x = StagedAttachment{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StagedAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StagedAttachment) ProtoMessage() {}

func (x *StagedAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StagedAttachment.ProtoReflect.Descriptor instead.
func (*StagedAttachment) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *StagedAttachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StagedAttachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StagedAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StagedAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *StagedAttachment) GetStagedDescriptor() []byte {
	if x != nil {
		return x.StagedDescriptor
	}
	return nil
}

func (x *StagedAttachment) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *StagedAttachment) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *StagedAttachment) GetPlaintextBytes() int64 {
	if x != nil {
		return x.PlaintextBytes
	}
	return 0
}

func (x *StagedAttachment) GetPlaintextSha256() string {
	if x != nil {
		return x.PlaintextSha256
	}
	return ""
}

type MetaRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Meta          *LockMeta              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaRecord) Reset() {
	*x = MetaRecord{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRecord) ProtoMessage() {}

func (x *MetaRecord) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRecord.ProtoReflect.Descriptor instead.
func (*MetaRecord) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *MetaRecord) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *MetaRecord) GetMeta() *LockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type NamespaceQueryConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PreferredEngine string                 `protobuf:"bytes,1,opt,name=preferred_engine,json=preferredEngine,proto3" json:"preferred_engine,omitempty"`
	FallbackEngine  string                 `protobuf:"bytes,2,opt,name=fallback_engine,json=fallbackEngine,proto3" json:"fallback_engine,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NamespaceQueryConfig) Reset() {
	*x = NamespaceQueryConfig{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceQueryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceQueryConfig) ProtoMessage() {}

func (x *NamespaceQueryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceQueryConfig.ProtoReflect.Descriptor instead.
func (*NamespaceQueryConfig) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *NamespaceQueryConfig) GetPreferredEngine() string {
	if x != nil {
		return x.PreferredEngine
	}
	return ""
}

func (x *NamespaceQueryConfig) GetFallbackEngine() string {
	if x != nil {
		return x.FallbackEngine
	}
	return ""
}

type NamespaceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *NamespaceQueryConfig  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceConfig) Reset() {
	*x = NamespaceConfig{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceConfig) ProtoMessage() {}

func (x *NamespaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceConfig.ProtoReflect.Descriptor instead.
func (*NamespaceConfig) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *NamespaceConfig) GetQuery() *NamespaceQueryConfig {
	if x != nil {
		return x.Query
	}
	return nil
}

type QueueMessageMeta struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Type                     string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Queue                    string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Id                       string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	EnqueuedAtUnix           int64                  `protobuf:"varint,4,opt,name=enqueued_at_unix,json=enqueuedAtUnix,proto3" json:"enqueued_at_unix,omitempty"`
	UpdatedAtUnix            int64                  `protobuf:"varint,5,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Attempts                 int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts              int32                  `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	NotVisibleUntilUnix      int64                  `protobuf:"varint,8,opt,name=not_visible_until_unix,json=notVisibleUntilUnix,proto3" json:"not_visible_until_unix,omitempty"`
	VisibilityTimeoutSeconds int64                  `protobuf:"varint,9,opt,name=visibility_timeout_seconds,json=visibilityTimeoutSeconds,proto3" json:"visibility_timeout_seconds,omitempty"`
	Attributes               *structpb.Struct       `protobuf:"bytes,10,opt,name=attributes,proto3" json:"attributes,omitempty"`
	LastError                *structpb.Value        `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	PayloadBytes             int64                  `protobuf:"varint,12,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	PayloadContentType       string                 `protobuf:"bytes,13,opt,name=payload_content_type,json=payloadContentType,proto3" json:"payload_content_type,omitempty"`
	ExpiresAtUnix            *int64                 `protobuf:"varint,14,opt,name=expires_at_unix,json=expiresAtUnix,proto3,oneof" json:"expires_at_unix,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,15,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	PayloadDescriptor        []byte                 `protobuf:"bytes,16,opt,name=payload_descriptor,json=payloadDescriptor,proto3" json:"payload_descriptor,omitempty"`
	MetaDescriptor           []byte                 `protobuf:"bytes,17,opt,name=meta_descriptor,json=metaDescriptor,proto3" json:"meta_descriptor,omitempty"`
	LeaseId                  string                 `protobuf:"bytes,18,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseFencingToken        int64                  `protobuf:"varint,19,opt,name=lease_fencing_token,json=leaseFencingToken,proto3" json:"lease_fencing_token,omitempty"`
	LeaseTxnId               string                 `protobuf:"bytes,20,opt,name=lease_txn_id,json=leaseTxnId,proto3" json:"lease_txn_id,omitempty"`
	FailureAttempts          *int32                 `protobuf:"varint,21,opt,name=failure_attempts,json=failureAttempts,proto3,oneof" json:"failure_attempts,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueueMessageMeta) Reset() {
	*x = QueueMessageMeta{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessageMeta) ProtoMessage() {}

func (x *QueueMessageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessageMeta.ProtoReflect.Descriptor instead.
func (*QueueMessageMeta) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *QueueMessageMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueueMessageMeta) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueMessageMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueMessageMeta) GetEnqueuedAtUnix() int64 {
	if x != nil {
		return x.EnqueuedAtUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *QueueMessageMeta) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *QueueMessageMeta) GetNotVisibleUntilUnix() int64 {
	if x != nil {
		return x.NotVisibleUntilUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetVisibilityTimeoutSeconds() int64 {
	if x != nil {
		return x.VisibilityTimeoutSeconds
	}
	return 0
}

func (x *QueueMessageMeta) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *QueueMessageMeta) GetLastError() *structpb.Value {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *QueueMessageMeta) GetPayloadBytes() int64 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

func (x *QueueMessageMeta) GetPayloadContentType() string {
	if x != nil {
		return x.PayloadContentType
	}
	return ""
}

func (x *QueueMessageMeta) GetExpiresAtUnix() int64 {
	if x != nil && x.ExpiresAtUnix != nil {
		return *x.ExpiresAtUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QueueMessageMeta) GetPayloadDescriptor() []byte {
	if x != nil {
		return x.PayloadDescriptor
	}
	return nil
}

func (x *QueueMessageMeta) GetMetaDescriptor() []byte {
	if x != nil {
		return x.MetaDescriptor
	}
	return nil
}

func (x *QueueMessageMeta) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *QueueMessageMeta) GetLeaseFencingToken() int64 {
	if x != nil {
		return x.LeaseFencingToken
	}
	return 0
}

func (x *QueueMessageMeta) GetLeaseTxnId() string {
	if x != nil {
		return x.LeaseTxnId
	}
	return ""
}

func (x *QueueMessageMeta) GetFailureAttempts() int32 {
	if x != nil && x.FailureAttempts != nil {
		return *x.FailureAttempts
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x0elockd.internal\x1a\x1cgoogle/protobuf/struct.proto\"\xbf\x01\n" +
	"\x05Lease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\x03R\ffencingToken\x12\x15\n" +
	"\x06txn_id\x18\x05 \x01(\tR\x05txnId\x12!\n" +
	"\ftxn_explicit\x18\x06 \x01(\bR\vtxnExplicit\"\xbe\b\n" +
	"\bLockMeta\x12+\n" +
	"\x05lease\x18\x01 \x01(\v2\x15.lockd.internal.LeaseR\x05lease\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"state_etag\x18\x03 \x01(\tR\tstateEtag\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x03R\ffencingToken\x12)\n" +
	"\x10state_descriptor\x18\x06 \x01(\fR\x0fstateDescriptor\x122\n" +
	"\x15state_plaintext_bytes\x18\a \x01(\x03R\x13statePlaintextBytes\x12+\n" +
	"\x11published_version\x18\b \x01(\x03R\x10publishedVersion\x127\n" +
	"\n" +
	"attributes\x18\t \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\"\n" +
	"\rstaged_txn_id\x18\n" +
	" \x01(\tR\vstagedTxnId\x12*\n" +
	"\x11staged_state_etag\x18\v \x01(\tR\x0fstagedStateEtag\x126\n" +
	"\x17staged_state_descriptor\x18\f \x01(\fR\x15stagedStateDescriptor\x12?\n" +
	"\x1cstaged_state_plaintext_bytes\x18\r \x01(\x03R\x19stagedStatePlaintextBytes\x12%\n" +
	"\x0estaged_version\x18\x0e \x01(\x03R\rstagedVersion\x12[\n" +
	"\x11staged_attributes\x18\x0f \x03(\v2..lockd.internal.LockMeta.StagedAttributesEntryR\x10stagedAttributes\x12#\n" +
	"\rstaged_remove\x18\x10 \x01(\bR\fstagedRemove\x12<\n" +
	"\vattachments\x18\x11 \x03(\v2\x1a.lockd.internal.AttachmentR\vattachments\x12O\n" +
	"\x12staged_attachments\x18\x12 \x03(\v2 .lockd.internal.StagedAttachmentR\x11stagedAttachments\x12:\n" +
	"\x19staged_attachment_deletes\x18\x13 \x03(\tR\x17stagedAttachmentDeletes\x128\n" +
	"\x18staged_attachments_clear\x18\x14 \x01(\bR\x16stagedAttachmentsClear\x1aC\n" +
	"\x15StagedAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x05 \x01(\fR\n" +
	"descriptor\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\x12'\n" +
	"\x0fplaintext_bytes\x18\b \x01(\x03R\x0eplaintextBytes\x12)\n" +
	"\x10plaintext_sha256\x18\t \x01(\tR\x0fplaintextSha256\"\xbe\x02\n" +
	"\x10StagedAttachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12+\n" +
	"\x11staged_descriptor\x18\x05 \x01(\fR\x10stagedDescriptor\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\x12'\n" +
	"\x0fplaintext_bytes\x18\b \x01(\x03R\x0eplaintextBytes\x12)\n" +
	"\x10plaintext_sha256\x18\t \x01(\tR\x0fplaintextSha256\"N\n" +
	"\n" +
	"MetaRecord\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.lockd.internal.LockMetaR\x04meta\"j\n" +
	"\x14NamespaceQueryConfig\x12)\n" +
	"\x10preferred_engine\x18\x01 \x01(\tR\x0fpreferredEngine\x12'\n" +
	"\x0ffallback_engine\x18\x02 \x01(\tR\x0efallbackEngine\"M\n" +
	"\x0fNamespaceConfig\x12:\n" +
	"\x05query\x18\x01 \x01(\v2$.lockd.internal.NamespaceQueryConfigR\x05query\"\x89\a\n" +
	"\x10QueueMessageMeta\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12(\n" +
	"\x10enqueued_at_unix\x18\x04 \x01(\x03R\x0eenqueuedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x05 \x01(\x03R\rupdatedAtUnix\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\a \x01(\x05R\vmaxAttempts\x123\n" +
	"\x16not_visible_until_unix\x18\b \x01(\x03R\x13notVisibleUntilUnix\x12<\n" +
	"\x1avisibility_timeout_seconds\x18\t \x01(\x03R\x18visibilityTimeoutSeconds\x127\n" +
	"\n" +
	"attributes\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x125\n" +
	"\n" +
	"last_error\x18\v \x01(\v2\x16.google.protobuf.ValueR\tlastError\x12#\n" +
	"\rpayload_bytes\x18\f \x01(\x03R\fpayloadBytes\x120\n" +
	"\x14payload_content_type\x18\r \x01(\tR\x12payloadContentType\x12+\n" +
	"\x0fexpires_at_unix\x18\x0e \x01(\x03H\x00R\rexpiresAtUnix\x88\x01\x01\x12%\n" +
	"\x0ecorrelation_id\x18\x0f \x01(\tR\rcorrelationId\x12-\n" +
	"\x12payload_descriptor\x18\x10 \x01(\fR\x11payloadDescriptor\x12'\n" +
	"\x0fmeta_descriptor\x18\x11 \x01(\fR\x0emetaDescriptor\x12\x19\n" +
	"\blease_id\x18\x12 \x01(\tR\aleaseId\x12.\n" +
	"\x13lease_fencing_token\x18\x13 \x01(\x03R\x11leaseFencingToken\x12 \n" +
	"\flease_txn_id\x18\x14 \x01(\tR\n" +
	"leaseTxnId\x12.\n" +
	"\x10failure_attempts\x18\x15 \x01(\x05H\x01R\x0ffailureAttempts\x88\x01\x01B\x12\n" +
	"\x10_expires_at_unixB\x13\n" +
	"\x11_failure_attemptsB(Z&pkt.systems/lockd/internal/proto;protob\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_storage_proto_goTypes = []any{
	(*Lease)(nil),                // 0: lockd.internal.Lease
	(*LockMeta)(nil),             // 1: lockd.internal.LockMeta
	(*Attachment)(nil),           // 2: lockd.internal.Attachment
	(*StagedAttachment)(nil),     // 3: lockd.internal.StagedAttachment
	(*MetaRecord)(nil),           // 4: lockd.internal.MetaRecord
	(*NamespaceQueryConfig)(nil), // 5: lockd.internal.NamespaceQueryConfig
	(*NamespaceConfig)(nil),      // 6: lockd.internal.NamespaceConfig
	(*QueueMessageMeta)(nil),     // 7: lockd.internal.QueueMessageMeta
	nil,                          // 8: lockd.internal.LockMeta.StagedAttributesEntry
	(*structpb.Struct)(nil),      // 9: google.protobuf.Struct
	(*structpb.Value)(nil),       // 10: google.protobuf.Value
}
var file_storage_proto_depIdxs = []int32{
	0,  // 0: lockd.internal.LockMeta.lease:type_name -> lockd.internal.Lease
	9,  // 1: lockd.internal.LockMeta.attributes:type_name -> google.protobuf.Struct
	8,  // 2: lockd.internal.LockMeta.staged_attributes:type_name -> lockd.internal.LockMeta.StagedAttributesEntry
	2,  // 3: lockd.internal.LockMeta.attachments:type_name -> lockd.internal.Attachment
	3,  // 4: lockd.internal.LockMeta.staged_attachments:type_name -> lockd.internal.StagedAttachment
	1,  // 5: lockd.internal.MetaRecord.meta:type_name -> lockd.internal.LockMeta
	5,  // 6: lockd.internal.NamespaceConfig.query:type_name -> lockd.internal.NamespaceQueryConfig
	9,  // 7: lockd.internal.QueueMessageMeta.attributes:type_name -> google.protobuf.Struct
	10, // 8: lockd.internal.QueueMessageMeta.last_error:type_name -> google.protobuf.Value
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_storage_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
