// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/storage.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	FencingToken  int64                  `protobuf:"varint,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_internal_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_internal_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Lease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Lease) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Lease) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Lease) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type LockMeta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Lease               *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Version             int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	StateEtag           string                 `protobuf:"bytes,3,opt,name=state_etag,json=stateEtag,proto3" json:"state_etag,omitempty"`
	UpdatedAtUnix       int64                  `protobuf:"varint,4,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	FencingToken        int64                  `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	StateDescriptor     []byte                 `protobuf:"bytes,6,opt,name=state_descriptor,json=stateDescriptor,proto3" json:"state_descriptor,omitempty"`
	StatePlaintextBytes int64                  `protobuf:"varint,7,opt,name=state_plaintext_bytes,json=statePlaintextBytes,proto3" json:"state_plaintext_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LockMeta) Reset() {
	*x = LockMeta{}
	mi := &file_internal_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockMeta) ProtoMessage() {}

func (x *LockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockMeta.ProtoReflect.Descriptor instead.
func (*LockMeta) Descriptor() ([]byte, []int) {
	return file_internal_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *LockMeta) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *LockMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LockMeta) GetStateEtag() string {
	if x != nil {
		return x.StateEtag
	}
	return ""
}

func (x *LockMeta) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *LockMeta) GetFencingToken() int64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockMeta) GetStateDescriptor() []byte {
	if x != nil {
		return x.StateDescriptor
	}
	return nil
}

func (x *LockMeta) GetStatePlaintextBytes() int64 {
	if x != nil {
		return x.StatePlaintextBytes
	}
	return 0
}

type MetaRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Meta          *LockMeta              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaRecord) Reset() {
	*x = MetaRecord{}
	mi := &file_internal_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRecord) ProtoMessage() {}

func (x *MetaRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRecord.ProtoReflect.Descriptor instead.
func (*MetaRecord) Descriptor() ([]byte, []int) {
	return file_internal_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *MetaRecord) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *MetaRecord) GetMeta() *LockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type QueueMessageMeta struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Type                     string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Queue                    string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Id                       string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	EnqueuedAtUnix           int64                  `protobuf:"varint,4,opt,name=enqueued_at_unix,json=enqueuedAtUnix,proto3" json:"enqueued_at_unix,omitempty"`
	UpdatedAtUnix            int64                  `protobuf:"varint,5,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Attempts                 int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts              int32                  `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	NotVisibleUntilUnix      int64                  `protobuf:"varint,8,opt,name=not_visible_until_unix,json=notVisibleUntilUnix,proto3" json:"not_visible_until_unix,omitempty"`
	VisibilityTimeoutSeconds int64                  `protobuf:"varint,9,opt,name=visibility_timeout_seconds,json=visibilityTimeoutSeconds,proto3" json:"visibility_timeout_seconds,omitempty"`
	Attributes               *structpb.Struct       `protobuf:"bytes,10,opt,name=attributes,proto3" json:"attributes,omitempty"`
	LastError                *structpb.Value        `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	PayloadBytes             int64                  `protobuf:"varint,12,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	PayloadContentType       string                 `protobuf:"bytes,13,opt,name=payload_content_type,json=payloadContentType,proto3" json:"payload_content_type,omitempty"`
	ExpiresAtUnix            *int64                 `protobuf:"varint,14,opt,name=expires_at_unix,json=expiresAtUnix,proto3,oneof" json:"expires_at_unix,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,15,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	PayloadDescriptor        []byte                 `protobuf:"bytes,16,opt,name=payload_descriptor,json=payloadDescriptor,proto3" json:"payload_descriptor,omitempty"`
	MetaDescriptor           []byte                 `protobuf:"bytes,17,opt,name=meta_descriptor,json=metaDescriptor,proto3" json:"meta_descriptor,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueueMessageMeta) Reset() {
	*x = QueueMessageMeta{}
	mi := &file_internal_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessageMeta) ProtoMessage() {}

func (x *QueueMessageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessageMeta.ProtoReflect.Descriptor instead.
func (*QueueMessageMeta) Descriptor() ([]byte, []int) {
	return file_internal_proto_storage_proto_rawDescGZIP(), []int{3}
}

func (x *QueueMessageMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueueMessageMeta) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueMessageMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueMessageMeta) GetEnqueuedAtUnix() int64 {
	if x != nil {
		return x.EnqueuedAtUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *QueueMessageMeta) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *QueueMessageMeta) GetNotVisibleUntilUnix() int64 {
	if x != nil {
		return x.NotVisibleUntilUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetVisibilityTimeoutSeconds() int64 {
	if x != nil {
		return x.VisibilityTimeoutSeconds
	}
	return 0
}

func (x *QueueMessageMeta) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *QueueMessageMeta) GetLastError() *structpb.Value {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *QueueMessageMeta) GetPayloadBytes() int64 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

func (x *QueueMessageMeta) GetPayloadContentType() string {
	if x != nil {
		return x.PayloadContentType
	}
	return ""
}

func (x *QueueMessageMeta) GetExpiresAtUnix() int64 {
	if x != nil && x.ExpiresAtUnix != nil {
		return *x.ExpiresAtUnix
	}
	return 0
}

func (x *QueueMessageMeta) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QueueMessageMeta) GetPayloadDescriptor() []byte {
	if x != nil {
		return x.PayloadDescriptor
	}
	return nil
}

func (x *QueueMessageMeta) GetMetaDescriptor() []byte {
	if x != nil {
		return x.MetaDescriptor
	}
	return nil
}

var File_internal_proto_storage_proto protoreflect.FileDescriptor

const file_internal_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/storage.proto\x12\x0elockd.internal\x1a\x1cgoogle/protobuf/struct.proto\"\x85\x01\n" +
	"\x05Lease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\x03R\ffencingToken\"\x9c\x02\n" +
	"\bLockMeta\x12+\n" +
	"\x05lease\x18\x01 \x01(\v2\x15.lockd.internal.LeaseR\x05lease\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"state_etag\x18\x03 \x01(\tR\tstateEtag\x12&\n" +
	"\x0fupdated_at_unix\x18\x04 \x01(\x03R\rupdatedAtUnix\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x03R\ffencingToken\x12)\n" +
	"\x10state_descriptor\x18\x06 \x01(\fR\x0fstateDescriptor\x122\n" +
	"\x15state_plaintext_bytes\x18\a \x01(\x03R\x13statePlaintextBytes\"N\n" +
	"\n" +
	"MetaRecord\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.lockd.internal.LockMetaR\x04meta\"\xd7\x05\n" +
	"\x10QueueMessageMeta\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12(\n" +
	"\x10enqueued_at_unix\x18\x04 \x01(\x03R\x0eenqueuedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x05 \x01(\x03R\rupdatedAtUnix\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\a \x01(\x05R\vmaxAttempts\x123\n" +
	"\x16not_visible_until_unix\x18\b \x01(\x03R\x13notVisibleUntilUnix\x12<\n" +
	"\x1avisibility_timeout_seconds\x18\t \x01(\x03R\x18visibilityTimeoutSeconds\x127\n" +
	"\n" +
	"attributes\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x125\n" +
	"\n" +
	"last_error\x18\v \x01(\v2\x16.google.protobuf.ValueR\tlastError\x12#\n" +
	"\rpayload_bytes\x18\f \x01(\x03R\fpayloadBytes\x120\n" +
	"\x14payload_content_type\x18\r \x01(\tR\x12payloadContentType\x12+\n" +
	"\x0fexpires_at_unix\x18\x0e \x01(\x03H\x00R\rexpiresAtUnix\x88\x01\x01\x12%\n" +
	"\x0ecorrelation_id\x18\x0f \x01(\tR\rcorrelationId\x12-\n" +
	"\x12payload_descriptor\x18\x10 \x01(\fR\x11payloadDescriptor\x12'\n" +
	"\x0fmeta_descriptor\x18\x11 \x01(\fR\x0emetaDescriptorB\x12\n" +
	"\x10_expires_at_unixB(Z&pkt.systems/lockd/internal/proto;protob\x06proto3"

var (
	file_internal_proto_storage_proto_rawDescOnce sync.Once
	file_internal_proto_storage_proto_rawDescData []byte
)

func file_internal_proto_storage_proto_rawDescGZIP() []byte {
	file_internal_proto_storage_proto_rawDescOnce.Do(func() {
		file_internal_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_storage_proto_rawDesc), len(file_internal_proto_storage_proto_rawDesc)))
	})
	return file_internal_proto_storage_proto_rawDescData
}

var file_internal_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_storage_proto_goTypes = []any{
	(*Lease)(nil),            // 0: lockd.internal.Lease
	(*LockMeta)(nil),         // 1: lockd.internal.LockMeta
	(*MetaRecord)(nil),       // 2: lockd.internal.MetaRecord
	(*QueueMessageMeta)(nil), // 3: lockd.internal.QueueMessageMeta
	(*structpb.Struct)(nil),  // 4: google.protobuf.Struct
	(*structpb.Value)(nil),   // 5: google.protobuf.Value
}
var file_internal_proto_storage_proto_depIdxs = []int32{
	0, // 0: lockd.internal.LockMeta.lease:type_name -> lockd.internal.Lease
	1, // 1: lockd.internal.MetaRecord.meta:type_name -> lockd.internal.LockMeta
	4, // 2: lockd.internal.QueueMessageMeta.attributes:type_name -> google.protobuf.Struct
	5, // 3: lockd.internal.QueueMessageMeta.last_error:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_storage_proto_init() }
func file_internal_proto_storage_proto_init() {
	if File_internal_proto_storage_proto != nil {
		return
	}
	file_internal_proto_storage_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_storage_proto_rawDesc), len(file_internal_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_storage_proto_goTypes,
		DependencyIndexes: file_internal_proto_storage_proto_depIdxs,
		MessageInfos:      file_internal_proto_storage_proto_msgTypes,
	}.Build()
	File_internal_proto_storage_proto = out.File
	file_internal_proto_storage_proto_goTypes = nil
	file_internal_proto_storage_proto_depIdxs = nil
}
