version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"   # OTLP enabled inside the network
    ports:
      - "16686:16686"                  # UI only
    expose:
      - "4317"                         # OTLP/gRPC (internal to compose network)
      - "4318"                         # OTLP/HTTP (internal)
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:16686"]
      interval: 5s
      timeout: 3s
      retries: 20

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.137.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"   # host -> collector (OTLP/gRPC)
      - "4318:4318"   # host -> collector (OTLP/HTTP)
      - "13133:13133" # health
    depends_on:
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:13133/healthz"]
      interval: 5s
      timeout: 3s
      retries: 30
